name: my-CI-Lint-And-Test

on:
  workflow_dispatch: 


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BLITZAR_BACKEND: cpu

jobs:
  foundrycheck: # Modified from the foundry book: https://book.getfoundry.sh/config/continuous-integration
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0
      - name: Install dependencies
        run: solidity/scripts/install_deps.sh
      - name: Run tests without via-ir or optimization
        run: solidity/scripts/pre_forge.sh test
      - name: Run tests with via-ir but without optimization
        run: solidity/scripts/pre_forge.sh test --via-ir
      - name: Run tests with optimization but without via-ir
        run: solidity/scripts/pre_forge.sh test --optimize
      - name: Run tests with via-ir and optimization
        run: solidity/scripts/pre_forge.sh test --via-ir --optimize

